# Generated by Django 6.0.7 on 2026-07-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('home', 'Home'), ('course', 'Course'), ('about', 'About Us'), ('placement', 'Placement'), ('contact', 'Contact'), ('blog', 'Blogs'), ('faq', 'FAQ')], default='course', max_length=20)),
                ('description', models.TextField()),
                ('keywords', models.CharField(blank=True, help_text='Comma separated keywords to help the search engine match this content', max_length=500)),
                ('url', models.CharField(blank=True, help_text='Relative/absolute page link', max_length=300)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
